
# A version of matrix which can cahce it's computing result of solve

makeCacheMatrix <- function(m = matrix()) {
  # make a matrix which is able to cache it's inverse when inversing use cacheSolve()
  #
  #   Args:
  #    m: The matrix want to cache it's inverse result
  #
  #   Returns:
  #     An matrix m that is compatible with cacheSolve(), use m$get() to get origin matrix
  inv <- NULL
  set <- function(y) {
    m <<- y
    inv <<- NULL
  }
  get <- function() m
  setinv <- function(inversed.matrix) inv <<- inversed.matrix
  getinv <- function() inv
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)
}


## Write a short comment describing this function

cacheSolve <- function(x) {
  # calculate inverse matrix from a chche matrix object.
  #
  # Args:
  #   x: an cache matrix object generated by makeCacheMatrix()
  #
  # Returns:
  #   a matrix that is the inverse of 'x'
  inv <- x$getinv()
  if(!is.null(inv)) {
    message("getting cached data")
    return(inv)
  }
  data <- x$get()
  inv <- solve(data)
  x$setinv(inv)
  inv
}
